
export enum ResponsesCodes {
    DEFAULT = 0,
    LOGIN_FAILED=1,
    LOGIN_WARNING_MAIL_CONFIRMATION=2,
    LOGIN_SUCCESS=3,
    SIGNUP_FAILED_EXISTING_MAIL=4,
    SIGNUP_SUCCESS=5,
    SERVER_ERROR=6,
    FORGET_PASSWORD_SUCCESS=7,
    RESET_PASSWORD_SUCCESS=8,
    RESET_PASSWORD_EXPIRED_TOKEN=9,
    EDIT_PROJECT_TITLE_FAILED=10,
    EDIT_CARD_TITLE_FAILED=11

}